import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { cn } from '@/utils/cn'
import { Gluten } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });

const gluten = Gluten({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-gluten',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark ${gluten.variable} ${inter }`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
